repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: no-commit-to-branch
        args: [--branch, dev, --branch, main]
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries, "88", --wrap-descriptions, "88"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8
        types: [python]
        args:
          - --max-line-length=88
          - --ignore=E731,E266,W504,E712

  - repo: https://github.com/crate-ci/typos
    rev: v1.34.0
    hooks:
      - id: typos
